# -*- coding: utf-8 -*-

import os

PICTURES_PATH = os.path.dirname(__file__)

BACKGROUND_IMAGE = os.path.join(PICTURES_PATH, 'background.png')

MAX_SPEED = 20

FIELD_WIDTH = 1200
FIELD_HEIGHT = 600

METER_1_COLOR = (0, 255, 70)
METER_2_COLOR = (232, 129, 31)

TEAMS_COUNT = 4
TEAM_DRONES_FRIENDLY_FIRE = True

DEBUG = False
# LOGLEVEL = 20  # INFO

MAX_HEALTH = 100
HEALTH_TOP_UP_SPEED = 0.5

MIN_ASTEROID_ELERIUM = 100
MAX_ASTEROID_ELERIUM = 200

MAX_DRONE_ELERIUM = 100

DRONE_SPEED = 3.77
DRONE_TURN_SPEED = 1.27
DRONE_CARGO_PAYLOAD = MAX_DRONE_ELERIUM

ASTEROID_ROTATION_SPEED = 0.27

CARGO_TRANSITION_SPEED = 1
CARGO_TRANSITION_DISTANCE = 10

# Fighting
DRONES_CAN_FIGHT = False
DRONE_DEAD_SPEED = 0.5
DRONE_DEAD_SPEED_DECELERATION = 0.0005
DRONE_MAX_SHIELD = MAX_HEALTH
DRONE_SHIELD_RENEWAL_RATE = 0.25

MOTHERSHIP_SAFE_DISTANCE = 200
MOTHERSHIP_MAX_SHIELD = 2000
MOTHERSHIP_SHIELD_RENEWAL_RATE = 0.15
MOTHERSHIP_HEALING_DISTANCE = 200
MOTHERSHIP_HEALING_RATE = 2

PROJECTILE_SPEED = 10
PROJECTILE_TTL = 60
PROJECTILE_DAMAGE = int(DRONE_MAX_SHIELD/3.5)

PLASMAGUN_COOLDOWN_TIME = 80
PLASMAGUN_COOLDOWN_RATE = 2

# For more see robogame_engine.constants

